sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  - secure: "pSt5eAz7TPWAu2cmmCd+Im5bh+347Hk7KnEkuxRUVMWJkLh06fHr7Or5XqNj7SXhyNxG+Fp0HcR/WIhsNYBzXFm2mmus8eB6ZbKaWbPyJP/NVUMjCmCZPP3Q0uVRnrF8r/u3tdSfM4F6p6ScQwoKdJUtD9NMHJKfPyQuy1l6/gddnVOWQRsS/cl+m3z3BiOshGdQSS5zMl4aoTeVQB4No9M7u/Kj5wy0UdyrOOS2i8wNE6PRaEt4R02pgYmM5A3ds/rRW1G8TpEwg5QRbOr7amGnBySCiAVmrVj0+3kyJlj+iORSLNEo/nnQSE6RqwhuhVB65Dw4l9IfxH51hUdtQSp2gKRZg8UEcCGZhxIJuer6kVCGTLi+gOJhdCPlImcLOBzMEWX6ZjIX6xyEYaVBhus/aC4NZYGuRadVOa252eD8ohn33qlpV4YbARVfj1zBPuEml2qyy5zK75Ck8oP9L/1U4atLkS4mdoMp6gukskNnPOrrcemfw9T24z19GSMEV0z3uLs/xhYljXRLvk3Y2nr9d2s2BhSgmSafnoCyZOP4UrPlBM9gXEOOg+2xtSW4awn4Y0EhAiCVHgqQ2n5Q4g8qU7b+OZmG9tnhx0FGB8nC5Mu5JHZOh2Spw4AarNL7bRf46mxCZYTAJRrThZjdI0gR5q3qR78Ni7XwsXmVvQ4="

after_success:
- python addsettings.py
- mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml
cache:
  directories:
  - "$HOME/.m2"
